version: '3'
services:
    php-unit:
        build: .
        container_name: php-unit
        image: littleof/centos-php-unit:latest
        env_file: .unitd.env
        volumes:
            - ./src/:/app-src/
            - ./entrypoint.d/:/entrypoint.d/
        ports:
            - '9580:9580'
        restart: always
        networks:
            - app_net
networks:
    app_net:
        driver: bridge
